language: python
python: 3.7
dist: xenial
sudo: true
install:
  - pip install --upgrade pip
  - pip install mkdocs mkdocs-material pymdown-extensions pygments
script:
  - mkdocs build --verbose --clean
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: book.mathit.ru
  local_dir: site
  on:
    branch: master